### ISSUE TITLE
Package is not installable

### ISSUE THREAD

**Issue by rnkhouse** [mjanser/ansible-role-phpmyadmin#2]
Hi, I tried with `ubuntu/trusty64` because what you have in your Vagrantfile is not available.

    fatal: [127.0.0.1]: FAILED! => {"cache_update_time": 1502918992, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'phpmyadmin'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n phpmyadmin : Depends: php but it is not installable\n              Depends: php-cli but it is not installable\n              Depends: php-mysql but it is not installable\n              Depends: php-json but it is not installable\n              Depends: php-mbstring but it is not installable\n              Depends: php-xml but it is not installable\n              Recommends: php-curl but it is not installable\n              Recommends: php-gd but it is not installable\n              Recommends: php-bz2 but it is not installable\n              Recommends: php-zip but it is not installable\n              Recommends: php-tcpdf but it is not going to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " phpmyadmin : Depends: php but it is not installable", "              Depends: php-cli but it is not installable", "              Depends: php-mysql but it is not installable", "              Depends: php-json but it is not installable", "              Depends: php-mbstring but it is not installable", "              Depends: php-xml but it is not installable", "              Recommends: php-curl but it is not installable", "              Recommends: php-gd but it is not installable", "              Recommends: php-bz2 but it is not installable", "              Recommends: php-zip but it is not installable", "              Recommends: php-tcpdf but it is not going to be installed"]}

**Comment by mjanser** [comment]
As stated in README.md this role is not maintained anymore, but there are plenty of other roles you can try, see https://galaxy.ansible.com/list#/roles?autocomplete=phpmyadmin.
